---
  region: us-west-2
  credentials:
    access-key-env-var: AWS_ACCESS_KEY_ID
    secret-key-env-var: AWS_SECRET_ACCESS_KEY
  timeout: 5000000
  poll-timeout: 70000000
  domain: hello-world
  bucket: swiftnav-hello-world
  prefix: zomg10
